---
- name: Reseting ufw
  ufw:
    state: reset
- name: Configure ufw
  ufw:
    policy: deny
    logging: medium
- name: Allow ssh port
  ufw:
    rule: limit
    port: '{{ansible_facts.env.get("SSH_CONNECTION", "... 22").split(" ")[-1]}}'
- name: Allow http port
  ufw:
    rule: allow
    port: http
- name: Allow https port
  ufw:
    rule: allow
    port: https
- name: Apply ufw
  ufw:
    state: enabled