---
- hosts: prod
  tasks:
    - name: Upload
      include_tasks: tasks/upload.yaml
    - name: Ticker
      include_tasks: tasks/ticker.yaml
    - name: Shirts
      include_tasks: tasks/shirts.yaml
    - name: Caddy
      include_tasks: tasks/caddy.yaml