name: Production deliver
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      DO_API_KEY: ${{ secrets.DO_API_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PAT2 }}'
          submodules: recursive

      - name: Write ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      
      - name: Install Taskfile.dev deb
        run: sudo apt install https://github.com/go-task/task/releases/download/v3.0.0/task_linux_386.deb

      - name: Build ticker
        run: task build
        working-directory: ./data/ticker/

      - name: Build foodrec
        run: task build
        working-directory: ./data/foodrec/

      - name: Buildnig invntory
        run: python3 build_inventory.py

      - name: Ansible cache redis
        run: ansible-playbook playbooks/cache/redis.yaml

      - name: Ansible machines upload
        run: ansible-playbook playbooks/machines/upload.yaml

      - name: Ansible machines shirts
        run: ansible-playbook playbooks/machines/shirts.yaml

      - name: Ansible machines ticker
        run: ansible-playbook playbooks/machines/ticker.yaml

      - name: Ansible machines foodrec
        run: ansible-playbook playbooks/machines/foodrec.yaml

      - name: Ansible machines caddy
        run: ansible-playbook playbooks/machines/caddy.yaml

      - name: Install datadog role ansible from galaxy
        run: pip install pyyaml datadog packaging && ansible-galaxy install datadog.datadog

      - name: Ansible datadog
        run: ansible-playbook playbooks/datadog.yaml