name: Deliver
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SP: ${{ secrets.SP }}
      ANSIBLE_HOST_KEY_CHECKING: "False"
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PAT2 }}'
          submodules: recursive

      - name: Ticker build
        run: ./build.sh
        working-directory: ./data/ticker/

      - name: Ansible
        run: |
          echo "

          [all:vars]
          ansible_connection=ssh
          ansible_user=root
          ansible_ssh_pass=$SP
          " >> inventory.cfg

          ansible-playbook playbooks/deploy.yaml