name: Deliver
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.PAT2 }}'
          submodules: recursive

      - name: Write ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Ticker build
        run: ./build.sh
        working-directory: ./data/ticker/

      - name: Ansible upload
        run: ansible-playbook playbooks/machines/upload.yaml

      - name: Ansible shirts
        run: ansible-playbook playbooks/machines/shirts.yaml

      - name: Ansible ticker
        run: ansible-playbook playbooks/machines/ticker.yaml

      - name: Ansible caddy
        run: ansible-playbook playbooks/machines/caddy.yaml

      - name: Install datadog role ansible from galaxy
        run: ansible-galaxy install datadog.datadog