---
- hosts: machines
  tasks:
  - name: Uploading static
    synchronize:
      src: ../../data/server/static
      dest: /data/
  - name: Uploading codetee backend
    synchronize:
      src: ../../data/codetee-backend-go
      dest: /opt/codetee
  - name: Uploading ticker backend
    synchronize:
      src: ../../data/ticker-backend-go/dist/
      dest: /opt/ticker/
  - name: Uploading dvarghare backend
    synchronize:
      src: ../../data/dvarghare-backend-python/
      dest: /opt/dvarghare/
